<?php
/**
 * @file
 * beekeeper_swarms.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function beekeeper_swarms_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_swarm_collect_details'.
  $field_bases['field_swarm_collect_details'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_swarm_collect_details',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  // Exported field_base: 'field_swarm_collector'.
  $field_bases['field_swarm_collector'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_swarm_collector',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => 'No',
        1 => 'Collect swarms',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  return $field_bases;
}
